### ISSUE TITLE
Update tree sitter grammar repo for java

### ISSUE THREAD

**Issue by meain** [emacs-tree-sitter/elisp-tree-sitter#182]
Java grammar in https://github.com/tree-sitter/tree-sitter-java has a significant change in how it handles switch statements. It would be great if the grammar here could be updated to the latest version if that is not blocked by anything else.

I am the maintainer of the [evil-textobj-tree-sitter](https://github.com/meain/evil-textobj-tree-sitter) package and recently found that this caused an issue as we are sharing the queries with the neovim counterpart as they have updated the queries to work with the new grammar.

ref: https://github.com/meain/evil-textobj-tree-sitter/issues/30

**Comment by ubolonton** [comment]
This was fixed by https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/56.
