### ISSUE TITLE
Syntax highlighting issues with template string literals in JavaScript and TypeScript

### ISSUE THREAD

**Issue by eeshugerman** [emacs-tree-sitter/elisp-tree-sitter#187]
I'm not sure if this is the right repo for this issue, so feel free to point me elsewhere.

![image](https://user-images.githubusercontent.com/25518211/143907049-8746a8cb-7472-465f-a500-fcf63b544bc0.png)

```js
const foo = 1;

`bar`; "bar"; // ok, just for reference

foo;
`${foo} bar`; // "foo" is the wrong color

foo.toString;
`${foo.toString} bar`; // "foo" is the wrong color (rest is ok)

1;
`${1} bar`; // ok

1 + 1 === 1;
`${1 + 1 === 1} bar`; // operators are the wrong color

1 + new Date();
`${1 + new Date()} bar`; // "new" is the wrong color
```

Also (but of less importance than the issues above) it would be nice if `$`, `{`, and `}` did _not_ get the string color (like how GitHub does it), since they're not actually part of the string.

**Comment by ubolonton** [comment]
It's an issue with the highlighting queries in `tree-sitter-langs`, probably [here in javascript/highlights.scm]( https://github.com/emacs-tree-sitter/tree-sitter-langs/blob/81adcdc/queries/javascript/highlights.scm#L85).

You can try editing that file in your `tree-sitter-langs` directory and then running `revert-buffer` in the typescript buffer.

**Comment by eeshugerman** [comment]
Thanks for the pointers! I found that the issues are mostly fixed if I remove `template_string` from [this line](https://github.com/emacs-tree-sitter/tree-sitter-langs/blob/0b15f1e45e8e4e0128a518feb3af2b42f95ac37e/queries/javascript/highlights.scm#L85) so that it's just `(string) @string`.

As for the remaining issues, from here it gets weird: the syntax highlighting actually changes slightly when I edit a buffer (e.g just adding newline). (I didn't notice this before, but it happens both with and without the fix described above.) The syntax highlighting is slightly off both before and after I edit the buffer, but in different ways.

Here's a video (don't mind the new color theme):
https://user-images.githubusercontent.com/25518211/144759507-d58b8f05-90a9-4695-b4ad-bd84aea766d3.mp4

I'm not seeing this with `emacs -Q`, so I suppose it's another package interfering. Any chance you've seen something like this before?

**Comment by eeshugerman** [comment]
OK I think I got it worked out, please see the draft PR above. I left it as a draft for now because of the question about variable references.
