### ISSUE TITLE
Java grammar not fully recognized

### ISSUE THREAD

**Issue by asmodeus812** [emacs-tree-sitter/elisp-tree-sitter#198]
Hi, I have just enabled tree sitter with emacs, and i am facing a weird issue where the java grammar is not correctly colouring the symbols, while other grammars (such as the ts or c/c++ do seem to work fine) Below i have provided a sample screenshot for different languages. I am using the doom themes pack (but even without a theme enabled, I see the same issues). I am also using LSP but have disabled highlighting with:
```  
     lsp-enable-semantic-highlighting nil
     lsp-semantic-tokens-enable nil
```

Here is the java colouring scheme, as you can see member variable (userRegistry) and function parameters are not coloured at all in the body or in the function header
![image](https://user-images.githubusercontent.com/15955811/146505287-4142e61a-5ba0-496e-8ab4-aea2c14f98bd.png)
Another sample in C where for some reason the block_alignment is not coloured in the function header and the places where it is used, but is coloured only in the assignment expression ?
![image](https://user-images.githubusercontent.com/15955811/146505679-4d8f44a8-7277-4cdd-993f-de35bbcdb9f1.png)
Another simple example in TS, where a keyword (this) is coloured the same as a function, and void which you can either count as a keyword or a type is again the same colour as a function declaration/definition.
![image](https://user-images.githubusercontent.com/15955811/146506431-97c51dc6-7c3a-4ce3-8a05-abb14b758a24.png)

Over all there are vast inconsistencies between very simple language constructs as member attributes, function definitions/declarations, function arguments, variables etc. I assume those are defined to be understood by default in the grammar as they seem obvious enough.

**Comment by ubolonton** [comment]
> Hi, I have just enabled tree sitter with emacs, and i am facing a weird issue where the java grammar is not correctly colouring the symbols, while other grammars (such as the ts or c/c++ do seem to work fine) 

Please report language-specific issues to [tree-sitter-langs](https://github.com/emacs-tree-sitter/tree-sitter-langs) or upstream grammar repositories.

To help troubleshooting, it's better to include texts that can be copied.

> Here is the java colouring scheme, as you can see member variable (userRegistry) and function parameters are not coloured at all in the body or in the function header 
>
> Another sample in C where for some reason the block_alignment is not coloured in the function header and the places where it is used, but is coloured only in the assignment expression ? 

Please check https://github.com/emacs-tree-sitter/tree-sitter-langs#highlighting-queries.

> Another simple example in TS, where a keyword (this) is coloured the same as a function, and void which you can either count as a keyword or a type is again the same colour as a function declaration/definition.
>
> Over all there are vast inconsistencies between very simple language constructs as member attributes, function definitions/declarations, function arguments, variables etc. I assume those are defined to be understood by default in the grammar as they seem obvious enough.

They should be understood by the grammars. How they are highlighted is a different issue. You can use `M-x what-cursor-position` to see what a piece of text is highlighted with. For how they are highlighted, check [the doc on syntax highlighting](https://emacs-tree-sitter.github.io/syntax-highlighting/).
