### ISSUE TITLE
How do I add a new grammer to this mode?

### ISSUE THREAD

**Issue by hhamud** [emacs-tree-sitter/elisp-tree-sitter#257]
I would like to add a new tree-sitter grammar to this mode such that when a users calls the function `tree-sitter-hl-mode` it will use that tree-sitter mode.

**Comment by jcs090218** [comment]
You might want to look at the [tree-sitter-langs](https://github.com/emacs-tree-sitter/tree-sitter-langs) repo instead.

Some references: 

- https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/175
- https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/165
- https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/166
- https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/119

**Comment by jcs090218** [comment]
I think this can be closed by now? Thanks! :)
